version: "3.7"
services:
  database:
    image: postgres:12.4
    env_file:
      - ./.env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mdschallenge -d mdschallenge" ]
      interval: 30s
      timeout: 20s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTS_FILE: requirements/production.txt
        ENVIRONMENT: production
    env_file:
      - ./.env
    volumes:
      - ./:/my_app
    command: bash -c "./wait-for-it.sh -t 300 database:5432 -t 300 rabbitmq:5672 && ./run.sh"
    expose:
      - 8000
    depends_on:
      - database
      - rabbitmq
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health-check" ]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./static:/data/www/static
    ports:
      - 3000:8080
    command: sh -c "/wait-for-it.sh -t 300 backend:8000 && nginx -g \"daemon off;\""
    depends_on:
      - backend

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health-check" ]
      interval: 30s
      timeout: 20s
      retries: 3

  ##########################################################
  #     Queueing stuff
  ##########################################################
  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3.8.16-management
    ports:
      - 15672:15672
    expose:
      - 5672
    env_file:
      - ./.env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 20s
      retries: 3

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTS_FILE: requirements/production.txt
        ENVIRONMENT: production
    command: bash -c "./wait-for-it.sh -t 300 database:5432 -t 300 rabbitmq:5672 && ./worker.sh"
    env_file:
      - ./.env
    volumes:
      - ./:/my_app
    depends_on:
      - rabbitmq
      - database
    healthcheck:
      test: celery -A configuration inspect ping
      interval: 30s
      timeout: 20s
      retries: 3
