# Generated by Django 4.0.2 on 2022-07-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_add_countries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "country", "verbose_name_plural": "countries"},
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={"verbose_name": "stock", "verbose_name_plural": "stock"},
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
