# Generated by Django 4.0.2 on 2022-07-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_add_db_index_to_product_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(db_index=True, max_length=5, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("product", "country")},
        ),
    ]
